version: "3"

services:
  accountable-tests:
    container_name: accountable-tests
    image: node:10
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3005:3005"
    command: /bin/bash -c 'npm install; npm run test;'
    networks:
      - accountable

networks:
  accountable:
